### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by VP08** [Gabriel-Desharnais/Modis-python-suite#10]
Salut Gabriel,

Nous avons encore des problèmes de connection avec NSIDC, leur serveur est down donc nous devons juste attendre, par contre cela force le programme à s'arrêter même lorsque qu'on demande un téléchargement des images MOD09 uniquement, sur le site de la NASA (URL2="https://e4ftl01.cr.usgs.gov") qui lui fonctionne, il y -t-il moyen de découpler les deux ?

Merci!
Véronique

**Comment by Gabriel-Desharnais** [comment]
C'est possible, la mise à jour devrait être dispo jeudi matin

**Comment by Gabriel-Desharnais** [comment]
Ce problème est réglé, les deux authentifications sont découplées. En cas d'erreur d'authentification, un message «NSIDC authentication error» ou «USGS authentication error» sera affiché.
